# Use the official Mosquitto image as the base image
FROM eclipse-mosquitto:latest

# Copy any custom configuration files
COPY mosquitto.conf /mosquitto/config/mosquitto.conf

# Expose MQTT port
EXPOSE 1883

# Start Mosquitto service
CMD ["mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
