apiVersion: v1
kind: Service
metadata:
  name: gas-pump-mqtt5-mqtt
  namespace: egs-fuellink
spec:
  type: ClusterIP
  selector:
    app: gas-pump-mqtt5
  ports:
  - port: 1883

---
apiVersion: v1
kind: Service
metadata:
  name: gas-pump-mqtt5-ws
  namespace: egs-fuellink
spec:
  type: ClusterIP
  selector:
    app: gas-pump-mqtt5
  ports:
  - port: 8000