apiVersion: apps/v1
kind: Deployment
metadata:
  name: gas-pump-mqtt5
  namespace: egs-fuellink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gas-pump-mqtt5
  template:
    metadata:
      labels:
        app: gas-pump-mqtt5
    spec:
      containers:
      - name: gas-pump-mqtt5
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
        - containerPort: 8000
        volumeMounts:
        - mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
          name: config
        - mountPath: /mosquitto/data/
          name: data
      volumes:
      - name: config
        configMap:
          name: gas-pump-mqtt5-config2
      - name: data
        persistentVolumeClaim:
          claimName: gas-pump-mqtt5-data2