apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gas-pump-mqtt5-claim0
  name: gas-pump-mqtt5-claim0
  namespace: egs-fuellink
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
