---
apiVersion: v1
kind: Service
metadata:
  name: ditto
  namespace: egs-fuellink
spec:
  type: NodePort
  selector:
    app: ditto-nginx
  ports:
    - port: 80
      nodePort: 30080
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ditto-nginx
  name: ditto-nginx
  namespace: egs-fuellink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ditto-nginx
  template:
    metadata:
      labels:
        app: ditto-nginx
    spec:
      initContainers:
        - name: wait-for-gateway
          image: curlimages/curl:latest
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [[ "$(curl -sL -w "%{http_code}\n" http://gateway:8080/health -o /dev/null)" != "200" ]]; do
                echo '.'
                sleep 15;
              done
      containers:
      - name: ditto-nginx
        image: docker.io/nginx:1.26-alpine
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-htpasswd
          mountPath: /etc/nginx/nginx.htpasswd
          subPath: nginx.htpasswd
        - name: nginx-cors
          mountPath: /etc/nginx/nginx-cors.conf
          subPath: nginx-cors.conf
        - name: nginx-index
          mountPath: /etc/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-conf
        configMap:
          name: ditto-nginx-conf
      - name: nginx-htpasswd
        configMap:
          name: ditto-nginx-htpasswd
      - name: nginx-cors
        configMap:
          name: ditto-nginx-cors
      - name: nginx-index
        configMap:
          name: ditto-nginx-index
